version: '3.1'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./data.json:/data.json
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

  mongo-seed:
    image: mongo:latest
    command: sh -c 'mongoimport --host mongodb --db nba --collection teams --type json --file /data.json --jsonArray'
    depends_on:
      - mongodb