version: '3.9'
services:

  postgres-wallet:
    container_name: postgres-nba
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres-nba://postgres:postgres@postgres:5432/postgres'
      GIN_MODE: release
    ports:
      - 8080:8080
    depends_on:
      - postgres-nba

volumes:
  pg-data:
